trigger:
  branches:
    include:
      - main
  paths:
    include:
      - site/**
      - api/**
      - infra/**

pool:
  name: SelfHostedPool

variables:
  DB_CONNECTION_STRING: $(CONNECTION_STRING)

stages:
  - stage: site
    displayName: "frontend"
    jobs:
      - job: build_and_deploy_site

        steps:
          - checkout: self

          - task: Npm@1
            inputs:
              command: "install"
              workingDir: "$(System.DefaultWorkingDirectory)/site"

          - task: Npm@1
            inputs:
              command: "custom"
              workingDir: "$(System.DefaultWorkingDirectory)/site"
              customCommand: "run build"

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: "ssh-azure-vm"
              sourceFolder: "$(System.DefaultWorkingDirectory)/site/dist"
              contents: "**"
              targetFolder: "/home/azadmin/site"
              cleanTargetFolder: true
              cleanHiddenFilesInTarget: true
              failOnEmptySource: true
              readyTimeout: "20000"

  - stage: api
    displayName: backend
    jobs:
      - job: build_and_deploy_api
        steps:
          - checkout: self

          - task: GoTool@0
            inputs:
              version: "1.10"

          - script: |
              sed 's/CONNECTION_STRING/$(DB_CONNECTION_STRING)/' -i api/main.go
            displayName: "Replace connection string"

          - script: |
              go build ./api/main.go
            displayName: "Build app"

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: "ssh-do-vm"
              sourceFolder: "$(System.DefaultWorkingDirectory)/api/"
              contents: "main"
              targetFolder: "/root/api"
              cleanTargetFolder: true
              cleanHiddenFilesInTarget: true
              readyTimeout: "20000"
              failOnEmptySource: true

  - stage: Infra
    displayName: "Infrastructure Stage"
    jobs:
      - job: DeployInfra
        steps:
          - script: echo "Deploying Infrastructure..."
            displayName: "Deploy Infrastructure"
