trigger:
  branches:
    include:
      - main
  paths:
    include:
      - site/**
      - api/**
      - infra/**

pool:
  name: SelfHostedPool

stages:
  - stage: site
    displayName: "Frontend"
    jobs:
      - job: build_site

        steps:
          - checkout: self


          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: '$(System.DefaultWorkingDirectory)/site'

          - task: Npm@1
            inputs:
              command: "custom"
              workingDir:  '$(System.DefaultWorkingDirectory)/site'
              customCommand: "run build"

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: "ssh-azure-vm"
              contents: $(System.DefaultWorkingDirectory)/site/dist/**'
              targetFolder: "/root/site"
              readyTimeout: "20000"
          # - task: PublishBuildArtifacts@1
          #   inputs:
          #     PathtoPublish: '$(System.DefaultWorkingDirectory)/site/dist'
          #     ArtifactName: "drop"
          #     publishLocation: "Container"

      - job: deploy_site

        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: "drop"
              targetPath: "$(Pipeline.Workspace)/drop"

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: "ssh-azure-vm"
              contents: "$(Pipeline.Workspace)/drop/**"
              targetFolder: "/root/site"
              readyTimeout: "20000"

  - stage: Backend
    displayName: "Backend Stage"
    jobs:
      - job: BuildBackend
        steps:
          - script: echo "Building Backend..."
            displayName: "Build Backend"

  - stage: Infra
    displayName: "Infrastructure Stage"
    jobs:
      - job: DeployInfra
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: echo "Deploying Infrastructure..."
            displayName: "Deploy Infrastructure"
