trigger:
  branches:
    include:
      - main
  paths:
    include:
      - site/**
      - api/**
      - infra/**

pool:
  name: SelfHostedPool

stages:
  - stage: site
    displayName: "Frontend"
    jobs:
      - job: build_and_deploy_site

        steps:
          - checkout: self

          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: '$(System.DefaultWorkingDirectory)/site'

          - task: Npm@1
            inputs:
              command: "custom"
              workingDir: '$(System.DefaultWorkingDirectory)/site'
              customCommand: "run build"
            
          - task: CmdLine@2
            inputs:
              script: |
                echo '$(System.DefaultWorkingDirectory)'
                echo "LS"
                ls 
                echo "DIST"
                ls '

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ssh-azure-vm'
              sourceFolder: '$(System.DefaultWorkingDirectory)/site/dist'
              contents: '**'
              targetFolder: '/home/azadmin/site'
              cleanTargetFolder: true
              cleanHiddenFilesInTarget: true
              readyTimeout: '20000'
              failOnEmptySource: true

          # - task: PublishBuildArtifacts@1
          #   inputs:
          #     PathtoPublish: '$(System.DefaultWorkingDirectory)/site/dist'
          #     ArtifactName: "drop"
          #     publishLocation: "Container"

  - stage: Backend
    displayName: "Backend Stage"
    jobs:
      - job: BuildBackend
        steps:
          - script: echo "Building Backend..."
            displayName: "Build Backend"

  - stage: Infra
    displayName: "Infrastructure Stage"
    jobs:
      - job: DeployInfra
        steps:
          - script: echo "Deploying Infrastructure..."
            displayName: "Deploy Infrastructure"
