- name: Configure API Service
  hosts: api
  become: yes # Run all tasks with elevated privileges

  tasks:
    - name: Set executable permissions on the API main file
      ansible.builtin.file:
        path: /root/api/main
        mode: "0755"

    - name: Create systemd service for CCS API
      ansible.builtin.template:
        src: ../resources/ccs_api.j2
        dest: /etc/systemd/system/ccs-api.service
      notify: Reload systemd daemon # Notify the handler to reload the daemon if the service file changes

    - name: Enable and start the CCS API service
      ansible.builtin.systemd:
        name: ccs-api
        enabled: yes
        state: started # Changed to started to ensure service is only started if enabled

  handlers:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
