- name: Configure webserver
  hosts: site
  become: true

  tasks:
    - name: Install NGINX
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Create NGINX server block
      ansible.builtin.template:
        src: ../resources/ccs_site.j2
        dest: /etc/nginx/sites-available/ccs_site
        mode: "0644"

    - name: Enable the site by creating a symbolic link
      ansible.builtin.file:
        src: /etc/nginx/sites-available/ccs_site
        dest: /etc/nginx/sites-enabled/ccs_site
        state: link

    - name: Set permissions for /home directory
      ansible.builtin.file:
        path: /home
        mode: "0755"

    - name: Set permissions for /home/azadmin directory
      ansible.builtin.file:
        path: /home/azadmin
        mode: "0755"

    - name: Ensure webgroup exists
      ansible.builtin.group:
        name: webgroup
        state: present

    - name: Add www-data user to webgroup
      ansible.builtin.user:
        name: www-data
        groups: webgroup
        append: yes

    - name: Add azadmin user to webgroup
      ansible.builtin.user:
        name: azadmin
        groups: webgroup
        append: yes

    - name: Set group ownership and permissions on site directory
      ansible.builtin.file:
        path: /home/azadmin/site
        owner: www-data
        group: webgroup
        mode: "2775"
        recurse: yes

    - name: Test NGINX configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Fail if NGINX configuration test fails
      ansible.builtin.fail:
        msg: "NGINX configuration test failed."
      when: nginx_test.rc != 0

    - name: Restart NGINX
      ansible.builtin.service:
        name: nginx
        state: restarted
